# Generated by Django 6.0.3 on 2026-04-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiusagelog',
            name='last_reset_month',
        ),
        migrations.RemoveField(
            model_name='aiusagelog',
            name='last_reset_year',
        ),
    ]
